In [1]:
import pandas as pd
import numpy as np

In [2]:
data= pd.read_csv("Dataset.csv")
df=pd.DataFrame(data)
print("the shape of datset is:",df.shape)
print("no of Rows:", df.shape[0])
print("no of Columns:", df.shape[1])

the shape of datset is: (31469, 64)
no of Rows: 31469
no of Columns: 64

In [3]:
df.head(4)

,Feedback_ID,ResponseType,Feedback_DateTime,Feedback_Month,FirstSeenTime_Date,NewUser_Period,ActiveEvents,CollabEvents,ReadEvents,MobileEvents,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,PipelineInfo_ClientCountry.1,Tenant_Country.1
0,flnps_v2_25ad287605f25432a0bd8cc846ac6147,Promoter,2/11/2021 13:13,2,7/26/2020 0:00,ExistingUser,757,99,236,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AU,Australia
1,flnps_v2_729938f9a67455f0b5de02ed0f5bb1ba,Detractor,2/18/2021 0:25,2,3/28/2020 0:00,ExistingUser,602,50,137,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QA,United Kingdom
2,flnps_v2_3fcce40270a65c08b0d70047015a8c64,Passive,1/31/2021 16:06,1,3/29/2020 0:00,ExistingUser,365,91,123,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JP,Denmark
3,flnps_v2_ba2385755c135fe3afc5c6b7b70c11ec,Passive,12/21/2020 9:22,12,3/5/2020 0:00,ExistingUser,937,213,490,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HK,United States

In [4]:
df.tail(4)

,Feedback_ID,ResponseType,Feedback_DateTime,Feedback_Month,FirstSeenTime_Date,NewUser_Period,ActiveEvents,CollabEvents,ReadEvents,MobileEvents,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,PipelineInfo_ClientCountry.1,Tenant_Country.1
31465,flnps_v2_255c48ac3dce5dc097841b05d55722ec,Promoter,2/26/2021 11:07,2,3/13/2020 0:00,ExistingUser,1269,39,325,354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GE,Georgia
31466,flnps_v2_44ab53d2449a522fafd61a9f94aca947,Promoter,12/6/2020 17:36,12,5/5/2020 0:00,ExistingUser,3160,892,1677,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PH,United Kingdom
31467,flnps_v2_244dde0ea6dc507eb51543d447efa74e,Passive,2/24/2021 11:42,2,10/10/2018 0:00,ExistingUser,1739,220,637,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CO,United States
31468,flnps_v2_c11f17d8628e5b45a87a6cb9419a398c,Detractor,2/22/2021 0:18,2,12/7/2020 0:00,New_In_Dec,329,8,33,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GB,United Kingdom

In [5]:
for i,column in enumerate (df.columns,start=1):
    print(i,':',column)

1 : Feedback_ID
2 : ResponseType
3 : Feedback_DateTime
4 : Feedback_Month
5 : FirstSeenTime_Date
6 : NewUser_Period
7 : ActiveEvents
8 : CollabEvents
9 : ReadEvents
10 : MobileEvents
11 : DesktopEvents
12 : WebEvents
13 : ChatCreateEvents
14 : ChannelCreateEvents
15 : FileCreateEvents
16 : CMDCreateEvents
17 : PlatformCreateEvents
18 : ActiveChannels
19 : ActiveTeams
20 : PipelineInfo_ClientCountry
21 : R7_DeviceInfo_CpuCores
22 : R7_DeviceInfo_CpuSpeed
23 : R7_DeviceInfo_CpuArchitecture
24 : Feedback_Rating
25 : Tenant_Country
26 : Tenant_MSSalesVerticalName
27 : Tenant_CustomerSegmentGroup
28 : Unnamed: 27
29 : Unnamed: 28
30 : Unnamed: 29
31 : Unnamed: 30
32 : Unnamed: 31
33 : Unnamed: 32
34 : Unnamed: 33
35 : Unnamed: 34
36 : Unnamed: 35
37 : Unnamed: 36
38 : Unnamed: 37
39 : Unnamed: 38
40 : Unnamed: 39
41 : Unnamed: 40
42 : Unnamed: 41
43 : Unnamed: 42
44 : Unnamed: 43
45 : Unnamed: 44
46 : Unnamed: 45
47 : Unnamed: 46
48 : Unnamed: 47
49 : Unnamed: 48
50 : Unnamed: 49
51 : Unnamed: 50
52 : Unnamed: 51
53 : Unnamed: 52
54 : Unnamed: 53
55 : Unnamed: 54
56 : Unnamed: 55
57 : Unnamed: 56
58 : Unnamed: 57
59 : Unnamed: 58
60 : Unnamed: 59
61 : Unnamed: 60
62 : Unnamed: 61
63 : PipelineInfo_ClientCountry.1
64 : Tenant_Country.1

In [6]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Feedback_ID,31469,31469,flnps_v2_25ad287605f25432a0bd8cc846ac6147,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ResponseType,31469,3,Promoter,13756,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Feedback_DateTime,31469,25375,2/26/2021 0:29,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Feedback_Month,31469.0,NaN,NaN,NaN,5.068607,5.011684,1.0,1.0,2.0,12.0,12.0
FirstSeenTime_Date,31469,1389,3/18/2020 0:00,331,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Unnamed: 59,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 60,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 61,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PipelineInfo_ClientCountry.1,31448,164,US,6218,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tenant_Country.1,31286,137,United States,9402,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [8]:
print("Total records:", len(df))
print("Unique Feedback IDs:", df["Feedback_ID"].nunique())
print(
    "Duplicate Feedback IDs:",
    df["Feedback_ID"].duplicated().sum()
)

Total records: 31469
Unique Feedback IDs: 31469
Duplicate Feedback IDs: 0

In [9]:
missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isna().sum(),
    "Missing_%": (df.isna().mean() * 100).round(2)
})

missing_summary.sort_values(
    "Missing_%",
    ascending=False
)

                                  Column  Missing_Count  Missing_%
Unnamed: 31                  Unnamed: 31          31469      100.0
Unnamed: 30                  Unnamed: 30          31469      100.0
Unnamed: 29                  Unnamed: 29          31469      100.0
Unnamed: 27                  Unnamed: 27          31469      100.0
Unnamed: 28                  Unnamed: 28          31469      100.0
...                                  ...            ...        ...
WebEvents                      WebEvents              0        0.0
ChatCreateEvents        ChatCreateEvents              0        0.0
ChannelCreateEvents  ChannelCreateEvents              0        0.0
FileCreateEvents        FileCreateEvents              0        0.0
CMDCreateEvents          CMDCreateEvents              0        0.0

[64 rows x 3 columns]

In [10]:
empty_columns=df.columns[
    df.isnull().all()
].tolist()
print("the complete empty columns")
print(empty_columns)

the complete empty columns
['Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61']

In [11]:
high_missing = missing_summary[
    missing_summary["Missing_%"] >= 95
].sort_values(
    "Missing_%",
    ascending=False
)

high_missing

,Column,Missing_Count,Missing_%
Unnamed: 27,Unnamed: 27,31469,100.00
Unnamed: 28,Unnamed: 28,31469,100.00
Unnamed: 29,Unnamed: 29,31469,100.00
Unnamed: 30,Unnamed: 30,31469,100.00
Unnamed: 46,Unnamed: 46,31469,100.00
Unnamed: 31,Unnamed: 31,31469,100.00
Unnamed: 32,Unnamed: 32,31469,100.00
Unnamed: 33,Unnamed: 33,31469,100.00
Unnamed: 34,Unnamed: 34,31469,100.00
Unnamed: 35,Unnamed: 35,31469,100.00
Unnamed: 36,Unnamed: 36,31469,100.00
Unnamed: 37,Unnamed: 37,31469,100.00
Unnamed: 38,Unnamed: 38,31469,100.00
Unnamed: 39,Unnamed: 39,31469,100.00
Unnamed: 40,Unnamed: 40,31469,100.00
Unnamed: 41,Unnamed: 41,31469,100.00
Unnamed: 42,Unnamed: 42,31469,100.00
Unnamed: 43,Unnamed: 43,31469,100.00
Unnamed: 44,Unnamed: 44,31469,100.00
Unnamed: 45,Unnamed: 45,31469,100.00
Unnamed: 54,Unnamed: 54,31469,100.00
Unnamed: 47,Unnamed: 47,31469,100.00
Unnamed: 48,Unnamed: 48,31469,100.00
Unnamed: 49,Unnamed: 49,31469,100.00
Unnamed: 50,Unnamed: 50,31469,100.00
Unnamed: 51,Unnamed: 51,31469,100.00
Unnamed: 52,Unnamed: 52,31469,100.00
Unnamed: 53,Unnamed: 53,31469,100.00
Unnamed: 58,Unnamed: 58,31469,100.00
Unnamed: 55,Unnamed: 55,31469,100.00
Unnamed: 56,Unnamed: 56,31469,100.00
Unnamed: 57,Unnamed: 57,31469,100.00
Unnamed: 60,Unnamed: 60,31469,100.00
Unnamed: 59,Unnamed: 59,31469,100.00
Unnamed: 61,Unnamed: 61,31469,100.00
R7_DeviceInfo_CpuArchitecture,R7_DeviceInfo_CpuArchitecture,31389,99.75

In [12]:
duplicate_columns = []

cols = df.columns

for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        if df[cols[i]].equals(df[cols[j]]):
            duplicate_columns.append(
                (cols[i], cols[j]))

duplicate_columns

[('PipelineInfo_ClientCountry', 'PipelineInfo_ClientCountry.1'),
 ('Tenant_Country', 'Tenant_Country.1'),
 ('Unnamed: 27', 'Unnamed: 28'),
 ('Unnamed: 27', 'Unnamed: 29'),
 ('Unnamed: 27', 'Unnamed: 30'),
 ('Unnamed: 27', 'Unnamed: 31'),
 ('Unnamed: 27', 'Unnamed: 32'),
 ('Unnamed: 27', 'Unnamed: 33'),
 ('Unnamed: 27', 'Unnamed: 34'),
 ('Unnamed: 27', 'Unnamed: 35'),
 ('Unnamed: 27', 'Unnamed: 36'),
 ('Unnamed: 27', 'Unnamed: 37'),
 ('Unnamed: 27', 'Unnamed: 38'),
 ('Unnamed: 27', 'Unnamed: 39'),
 ('Unnamed: 27', 'Unnamed: 40'),
 ('Unnamed: 27', 'Unnamed: 41'),
 ('Unnamed: 27', 'Unnamed: 42'),
 ('Unnamed: 27', 'Unnamed: 43'),
 ('Unnamed: 27', 'Unnamed: 44'),
 ('Unnamed: 27', 'Unnamed: 45'),
 ('Unnamed: 27', 'Unnamed: 46'),
 ('Unnamed: 27', 'Unnamed: 47'),
 ('Unnamed: 27', 'Unnamed: 48'),
 ('Unnamed: 27', 'Unnamed: 49'),
 ('Unnamed: 27', 'Unnamed: 50'),
 ('Unnamed: 27', 'Unnamed: 51'),
 ('Unnamed: 27', 'Unnamed: 52'),
 ('Unnamed: 27', 'Unnamed: 53'),
 ('Unnamed: 27', 'Unnamed: 54'),
 ('Unnamed: 27', 'Unnamed: 55'),
 ('Unnamed: 27', 'Unnamed: 56'),
 ('Unnamed: 27', 'Unnamed: 57'),
 ('Unnamed: 27', 'Unnamed: 58'),
 ('Unnamed: 27', 'Unnamed: 59'),
 ('Unnamed: 27', 'Unnamed: 60'),
 ('Unnamed: 27', 'Unnamed: 61'),
 ('Unnamed: 28', 'Unnamed: 29'),
 ('Unnamed: 28', 'Unnamed: 30'),
 ('Unnamed: 28', 'Unnamed: 31'),
 ('Unnamed: 28', 'Unnamed: 32'),
 ('Unnamed: 28', 'Unnamed: 33'),
 ('Unnamed: 28', 'Unnamed: 34'),
 ('Unnamed: 28', 'Unnamed: 35'),
 ('Unnamed: 28', 'Unnamed: 36'),
 ('Unnamed: 28', 'Unnamed: 37'),
 ('Unnamed: 28', 'Unnamed: 38'),
 ('Unnamed: 28', 'Unnamed: 39'),
 ('Unnamed: 28', 'Unnamed: 40'),
 ('Unnamed: 28', 'Unnamed: 41'),
 ('Unnamed: 28', 'Unnamed: 42'),
 ('Unnamed: 28', 'Unnamed: 43'),
 ('Unnamed: 28', 'Unnamed: 44'),
 ('Unnamed: 28', 'Unnamed: 45'),
 ('Unnamed: 28', 'Unnamed: 46'),
 ('Unnamed: 28', 'Unnamed: 47'),
 ('Unnamed: 28', 'Unnamed: 48'),
 ('Unnamed: 28', 'Unnamed: 49'),
 ('Unnamed: 28', 'Unnamed: 50'),
 ('Unnamed: 28', 'Unnamed: 51'),
 ('Unnamed: 28', 'Unnamed: 52'),
 ('Unnamed: 28', 'Unnamed: 53'),
 ('Unnamed: 28', 'Unnamed: 54'),
 ('Unnamed: 28', 'Unnamed: 55'),
 ('Unnamed: 28', 'Unnamed: 56'),
 ('Unnamed: 28', 'Unnamed: 57'),
 ('Unnamed: 28', 'Unnamed: 58'),
 ('Unnamed: 28', 'Unnamed: 59'),
 ('Unnamed: 28', 'Unnamed: 60'),
 ('Unnamed: 28', 'Unnamed: 61'),
 ('Unnamed: 29', 'Unnamed: 30'),
 ('Unnamed: 29', 'Unnamed: 31'),
 ('Unnamed: 29', 'Unnamed: 32'),
 ('Unnamed: 29', 'Unnamed: 33'),
 ('Unnamed: 29', 'Unnamed: 34'),
 ('Unnamed: 29', 'Unnamed: 35'),
 ('Unnamed: 29', 'Unnamed: 36'),
 ('Unnamed: 29', 'Unnamed: 37'),
 ('Unnamed: 29', 'Unnamed: 38'),
 ('Unnamed: 29', 'Unnamed: 39'),
 ('Unnamed: 29', 'Unnamed: 40'),
 ('Unnamed: 29', 'Unnamed: 41'),
 ('Unnamed: 29', 'Unnamed: 42'),
 ('Unnamed: 29', 'Unnamed: 43'),
 ('Unnamed: 29', 'Unnamed: 44'),
 ('Unnamed: 29', 'Unnamed: 45'),
 ('Unnamed: 29', 'Unnamed: 46'),
 ('Unnamed: 29', 'Unnamed: 47'),
 ('Unnamed: 29', 'Unnamed: 48'),
 ('Unnamed: 29', 'Unnamed: 49'),
 ('Unnamed: 29', 'Unnamed: 50'),
 ('Unnamed: 29', 'Unnamed: 51'),
 ('Unnamed: 29', 'Unnamed: 52'),
 ('Unnamed: 29', 'Unnamed: 53'),
 ('Unnamed: 29', 'Unnamed: 54'),
 ('Unnamed: 29', 'Unnamed: 55'),
 ('Unnamed: 29', 'Unnamed: 56'),
 ('Unnamed: 29', 'Unnamed: 57'),
 ('Unnamed: 29', 'Unnamed: 58'),
 ('Unnamed: 29', 'Unnamed: 59'),
 ('Unnamed: 29', 'Unnamed: 60'),
 ('Unnamed: 29', 'Unnamed: 61'),
 ('Unnamed: 30', 'Unnamed: 31'),
 ('Unnamed: 30', 'Unnamed: 32'),
 ('Unnamed: 30', 'Unnamed: 33'),
 ('Unnamed: 30', 'Unnamed: 34'),
 ('Unnamed: 30', 'Unnamed: 35'),
 ('Unnamed: 30', 'Unnamed: 36'),
 ('Unnamed: 30', 'Unnamed: 37'),
 ('Unnamed: 30', 'Unnamed: 38'),
 ('Unnamed: 30', 'Unnamed: 39'),
 ('Unnamed: 30', 'Unnamed: 40'),
 ('Unnamed: 30', 'Unnamed: 41'),
 ('Unnamed: 30', 'Unnamed: 42'),
 ('Unnamed: 30', 'Unnamed: 43'),
 ('Unnamed: 30', 'Unnamed: 44'),
 ('Unnamed: 30', 'Unnamed: 45'),
 ('Unnamed: 30', 'Unnamed: 46'),
 ('Unnamed: 30', 'Unnamed: 47'),
 ('Unnamed: 30', 'Unnamed: 48'),
 ('Unnamed: 30', 'Unnamed: 49'),
 ('Unnamed: 30', 'Unnamed: 50'),
 ('Unnamed: 30', 'Unnamed: 51'),
 ('Unnamed: 30', 'Unnamed: 52'),
 ('Unnamed: 30', 'Unnamed: 53'),
 ('Unnamed: 30', 'Unnamed: 54'),
 ('Unnamed: 30', 'Unnamed: 55'),
 ('Unnamed: 30', 'Unnamed: 56'),
 ('Unnamed: 30', 'Unnamed: 57'),
 ('Unnamed: 30', 'Unnamed: 58'),
 ('Unnamed: 30', 'Unnamed: 59'),
 ('Unnamed: 30', 'Unnamed: 60'),
 ('Unnamed: 30', 'Unnamed: 61'),
 ('Unnamed: 31', 'Unnamed: 32'),
 ('Unnamed: 31', 'Unnamed: 33'),
 ('Unnamed: 31', 'Unnamed: 34'),
 ('Unnamed: 31', 'Unnamed: 35'),
 ('Unnamed: 31', 'Unnamed: 36'),
 ('Unnamed: 31', 'Unnamed: 37'),
 ('Unnamed: 31', 'Unnamed: 38'),
 ('Unnamed: 31', 'Unnamed: 39'),
 ('Unnamed: 31', 'Unnamed: 40'),
 ('Unnamed: 31', 'Unnamed: 41'),
 ('Unnamed: 31', 'Unnamed: 42'),
 ('Unnamed: 31', 'Unnamed: 43'),
 ('Unnamed: 31', 'Unnamed: 44'),
 ('Unnamed: 31', 'Unnamed: 45'),
 ('Unnamed: 31', 'Unnamed: 46'),
 ('Unnamed: 31', 'Unnamed: 47'),
 ('Unnamed: 31', 'Unnamed: 48'),
 ('Unnamed: 31', 'Unnamed: 49'),
 ('Unnamed: 31', 'Unnamed: 50'),
 ('Unnamed: 31', 'Unnamed: 51'),
 ('Unnamed: 31', 'Unnamed: 52'),
 ('Unnamed: 31', 'Unnamed: 53'),
 ('Unnamed: 31', 'Unnamed: 54'),
 ('Unnamed: 31', 'Unnamed: 55'),
 ('Unnamed: 31', 'Unnamed: 56'),
 ('Unnamed: 31', 'Unnamed: 57'),
 ('Unnamed: 31', 'Unnamed: 58'),
 ('Unnamed: 31', 'Unnamed: 59'),
 ('Unnamed: 31', 'Unnamed: 60'),
 ('Unnamed: 31', 'Unnamed: 61'),
 ('Unnamed: 32', 'Unnamed: 33'),
 ('Unnamed: 32', 'Unnamed: 34'),
 ('Unnamed: 32', 'Unnamed: 35'),
 ('Unnamed: 32', 'Unnamed: 36'),
 ('Unnamed: 32', 'Unnamed: 37'),
 ('Unnamed: 32', 'Unnamed: 38'),
 ('Unnamed: 32', 'Unnamed: 39'),
 ('Unnamed: 32', 'Unnamed: 40'),
 ('Unnamed: 32', 'Unnamed: 41'),
 ('Unnamed: 32', 'Unnamed: 42'),
 ('Unnamed: 32', 'Unnamed: 43'),
 ('Unnamed: 32', 'Unnamed: 44'),
 ('Unnamed: 32', 'Unnamed: 45'),
 ('Unnamed: 32', 'Unnamed: 46'),
 ('Unnamed: 32', 'Unnamed: 47'),
 ('Unnamed: 32', 'Unnamed: 48'),
 ('Unnamed: 32', 'Unnamed: 49'),
 ('Unnamed: 32', 'Unnamed: 50'),
 ('Unnamed: 32', 'Unnamed: 51'),
 ('Unnamed: 32', 'Unnamed: 52'),
 ('Unnamed: 32', 'Unnamed: 53'),
 ('Unnamed: 32', 'Unnamed: 54'),
 ('Unnamed: 32', 'Unnamed: 55'),
 ('Unnamed: 32', 'Unnamed: 56'),
 ('Unnamed: 32', 'Unnamed: 57'),
 ('Unnamed: 32', 'Unnamed: 58'),
 ('Unnamed: 32', 'Unnamed: 59'),
 ('Unnamed: 32', 'Unnamed: 60'),
 ('Unnamed: 32', 'Unnamed: 61'),
 ('Unnamed: 33', 'Unnamed: 34'),
 ('Unnamed: 33', 'Unnamed: 35'),
 ('Unnamed: 33', 'Unnamed: 36'),
 ('Unnamed: 33', 'Unnamed: 37'),
 ('Unnamed: 33', 'Unnamed: 38'),
 ('Unnamed: 33', 'Unnamed: 39'),
 ('Unnamed: 33', 'Unnamed: 40'),
 ('Unnamed: 33', 'Unnamed: 41'),
 ('Unnamed: 33', 'Unnamed: 42'),
 ('Unnamed: 33', 'Unnamed: 43'),
 ('Unnamed: 33', 'Unnamed: 44'),
 ('Unnamed: 33', 'Unnamed: 45'),
 ('Unnamed: 33', 'Unnamed: 46'),
 ('Unnamed: 33', 'Unnamed: 47'),
 ('Unnamed: 33', 'Unnamed: 48'),
 ('Unnamed: 33', 'Unnamed: 49'),
 ('Unnamed: 33', 'Unnamed: 50'),
 ('Unnamed: 33', 'Unnamed: 51'),
 ('Unnamed: 33', 'Unnamed: 52'),
 ('Unnamed: 33', 'Unnamed: 53'),
 ('Unnamed: 33', 'Unnamed: 54'),
 ('Unnamed: 33', 'Unnamed: 55'),
 ('Unnamed: 33', 'Unnamed: 56'),
 ('Unnamed: 33', 'Unnamed: 57'),
 ('Unnamed: 33', 'Unnamed: 58'),
 ('Unnamed: 33', 'Unnamed: 59'),
 ('Unnamed: 33', 'Unnamed: 60'),
 ('Unnamed: 33', 'Unnamed: 61'),
 ('Unnamed: 34', 'Unnamed: 35'),
 ('Unnamed: 34', 'Unnamed: 36'),
 ('Unnamed: 34', 'Unnamed: 37'),
 ('Unnamed: 34', 'Unnamed: 38'),
 ('Unnamed: 34', 'Unnamed: 39'),
 ('Unnamed: 34', 'Unnamed: 40'),
 ('Unnamed: 34', 'Unnamed: 41'),
 ('Unnamed: 34', 'Unnamed: 42'),
 ('Unnamed: 34', 'Unnamed: 43'),
 ('Unnamed: 34', 'Unnamed: 44'),
 ('Unnamed: 34', 'Unnamed: 45'),
 ('Unnamed: 34', 'Unnamed: 46'),
 ('Unnamed: 34', 'Unnamed: 47'),
 ('Unnamed: 34', 'Unnamed: 48'),
 ('Unnamed: 34', 'Unnamed: 49'),
 ('Unnamed: 34', 'Unnamed: 50'),
 ('Unnamed: 34', 'Unnamed: 51'),
 ('Unnamed: 34', 'Unnamed: 52'),
 ('Unnamed: 34', 'Unnamed: 53'),
 ('Unnamed: 34', 'Unnamed: 54'),
 ('Unnamed: 34', 'Unnamed: 55'),
 ('Unnamed: 34', 'Unnamed: 56'),
 ('Unnamed: 34', 'Unnamed: 57'),
 ('Unnamed: 34', 'Unnamed: 58'),
 ('Unnamed: 34', 'Unnamed: 59'),
 ('Unnamed: 34', 'Unnamed: 60'),
 ('Unnamed: 34', 'Unnamed: 61'),
 ('Unnamed: 35', 'Unnamed: 36'),
 ('Unnamed: 35', 'Unnamed: 37'),
 ('Unnamed: 35', 'Unnamed: 38'),
 ('Unnamed: 35', 'Unnamed: 39'),
 ('Unnamed: 35', 'Unnamed: 40'),
 ('Unnamed: 35', 'Unnamed: 41'),
 ('Unnamed: 35', 'Unnamed: 42'),
 ('Unnamed: 35', 'Unnamed: 43'),
 ('Unnamed: 35', 'Unnamed: 44'),
 ('Unnamed: 35', 'Unnamed: 45'),
 ('Unnamed: 35', 'Unnamed: 46'),
 ('Unnamed: 35', 'Unnamed: 47'),
 ('Unnamed: 35', 'Unnamed: 48'),
 ('Unnamed: 35', 'Unnamed: 49'),
 ('Unnamed: 35', 'Unnamed: 50'),
 ('Unnamed: 35', 'Unnamed: 51'),
 ('Unnamed: 35', 'Unnamed: 52'),
 ('Unnamed: 35', 'Unnamed: 53'),
 ('Unnamed: 35', 'Unnamed: 54'),
 ('Unnamed: 35', 'Unnamed: 55'),
 ('Unnamed: 35', 'Unnamed: 56'),
 ('Unnamed: 35', 'Unnamed: 57'),
 ('Unnamed: 35', 'Unnamed: 58'),
 ('Unnamed: 35', 'Unnamed: 59'),
 ('Unnamed: 35', 'Unnamed: 60'),
 ('Unnamed: 35', 'Unnamed: 61'),
 ('Unnamed: 36', 'Unnamed: 37'),
 ('Unnamed: 36', 'Unnamed: 38'),
 ('Unnamed: 36', 'Unnamed: 39'),
 ('Unnamed: 36', 'Unnamed: 40'),
 ('Unnamed: 36', 'Unnamed: 41'),
 ('Unnamed: 36', 'Unnamed: 42'),
 ('Unnamed: 36', 'Unnamed: 43'),
 ('Unnamed: 36', 'Unnamed: 44'),
 ('Unnamed: 36', 'Unnamed: 45'),
 ('Unnamed: 36', 'Unnamed: 46'),
 ('Unnamed: 36', 'Unnamed: 47'),
 ('Unnamed: 36', 'Unnamed: 48'),
 ('Unnamed: 36', 'Unnamed: 49'),
 ('Unnamed: 36', 'Unnamed: 50'),
 ('Unnamed: 36', 'Unnamed: 51'),
 ('Unnamed: 36', 'Unnamed: 52'),
 ('Unnamed: 36', 'Unnamed: 53'),
 ('Unnamed: 36', 'Unnamed: 54'),
 ('Unnamed: 36', 'Unnamed: 55'),
 ('Unnamed: 36', 'Unnamed: 56'),
 ('Unnamed: 36', 'Unnamed: 57'),
 ('Unnamed: 36', 'Unnamed: 58'),
 ('Unnamed: 36', 'Unnamed: 59'),
 ('Unnamed: 36', 'Unnamed: 60'),
 ('Unnamed: 36', 'Unnamed: 61'),
 ('Unnamed: 37', 'Unnamed: 38'),
 ('Unnamed: 37', 'Unnamed: 39'),
 ('Unnamed: 37', 'Unnamed: 40'),
 ('Unnamed: 37', 'Unnamed: 41'),
 ('Unnamed: 37', 'Unnamed: 42'),
 ('Unnamed: 37', 'Unnamed: 43'),
 ('Unnamed: 37', 'Unnamed: 44'),
 ('Unnamed: 37', 'Unnamed: 45'),
 ('Unnamed: 37', 'Unnamed: 46'),
 ('Unnamed: 37', 'Unnamed: 47'),
 ('Unnamed: 37', 'Unnamed: 48'),
 ('Unnamed: 37', 'Unnamed: 49'),
 ('Unnamed: 37', 'Unnamed: 50'),
 ('Unnamed: 37', 'Unnamed: 51'),
 ('Unnamed: 37', 'Unnamed: 52'),
 ('Unnamed: 37', 'Unnamed: 53'),
 ('Unnamed: 37', 'Unnamed: 54'),
 ('Unnamed: 37', 'Unnamed: 55'),
 ('Unnamed: 37', 'Unnamed: 56'),
 ('Unnamed: 37', 'Unnamed: 57'),
 ('Unnamed: 37', 'Unnamed: 58'),
 ('Unnamed: 37', 'Unnamed: 59'),
 ('Unnamed: 37', 'Unnamed: 60'),
 ('Unnamed: 37', 'Unnamed: 61'),
 ('Unnamed: 38', 'Unnamed: 39'),
 ('Unnamed: 38', 'Unnamed: 40'),
 ('Unnamed: 38', 'Unnamed: 41'),
 ('Unnamed: 38', 'Unnamed: 42'),
 ('Unnamed: 38', 'Unnamed: 43'),
 ('Unnamed: 38', 'Unnamed: 44'),
 ('Unnamed: 38', 'Unnamed: 45'),
 ('Unnamed: 38', 'Unnamed: 46'),
 ('Unnamed: 38', 'Unnamed: 47'),
 ('Unnamed: 38', 'Unnamed: 48'),
 ('Unnamed: 38', 'Unnamed: 49'),
 ('Unnamed: 38', 'Unnamed: 50'),
 ('Unnamed: 38', 'Unnamed: 51'),
 ('Unnamed: 38', 'Unnamed: 52'),
 ('Unnamed: 38', 'Unnamed: 53'),
 ('Unnamed: 38', 'Unnamed: 54'),
 ('Unnamed: 38', 'Unnamed: 55'),
 ('Unnamed: 38', 'Unnamed: 56'),
 ('Unnamed: 38', 'Unnamed: 57'),
 ('Unnamed: 38', 'Unnamed: 58'),
 ('Unnamed: 38', 'Unnamed: 59'),
 ('Unnamed: 38', 'Unnamed: 60'),
 ('Unnamed: 38', 'Unnamed: 61'),
 ('Unnamed: 39', 'Unnamed: 40'),
 ('Unnamed: 39', 'Unnamed: 41'),
 ('Unnamed: 39', 'Unnamed: 42'),
 ('Unnamed: 39', 'Unnamed: 43'),
 ('Unnamed: 39', 'Unnamed: 44'),
 ('Unnamed: 39', 'Unnamed: 45'),
 ('Unnamed: 39', 'Unnamed: 46'),
 ('Unnamed: 39', 'Unnamed: 47'),
 ('Unnamed: 39', 'Unnamed: 48'),
 ('Unnamed: 39', 'Unnamed: 49'),
 ('Unnamed: 39', 'Unnamed: 50'),
 ('Unnamed: 39', 'Unnamed: 51'),
 ('Unnamed: 39', 'Unnamed: 52'),
 ('Unnamed: 39', 'Unnamed: 53'),
 ('Unnamed: 39', 'Unnamed: 54'),
 ('Unnamed: 39', 'Unnamed: 55'),
 ('Unnamed: 39', 'Unnamed: 56'),
 ('Unnamed: 39', 'Unnamed: 57'),
 ('Unnamed: 39', 'Unnamed: 58'),
 ('Unnamed: 39', 'Unnamed: 59'),
 ('Unnamed: 39', 'Unnamed: 60'),
 ('Unnamed: 39', 'Unnamed: 61'),
 ('Unnamed: 40', 'Unnamed: 41'),
 ('Unnamed: 40', 'Unnamed: 42'),
 ('Unnamed: 40', 'Unnamed: 43'),
 ('Unnamed: 40', 'Unnamed: 44'),
 ('Unnamed: 40', 'Unnamed: 45'),
 ('Unnamed: 40', 'Unnamed: 46'),
 ('Unnamed: 40', 'Unnamed: 47'),
 ('Unnamed: 40', 'Unnamed: 48'),
 ('Unnamed: 40', 'Unnamed: 49'),
 ('Unnamed: 40', 'Unnamed: 50'),
 ('Unnamed: 40', 'Unnamed: 51'),
 ('Unnamed: 40', 'Unnamed: 52'),
 ('Unnamed: 40', 'Unnamed: 53'),
 ('Unnamed: 40', 'Unnamed: 54'),
 ('Unnamed: 40', 'Unnamed: 55'),
 ('Unnamed: 40', 'Unnamed: 56'),
 ('Unnamed: 40', 'Unnamed: 57'),
 ('Unnamed: 40', 'Unnamed: 58'),
 ('Unnamed: 40', 'Unnamed: 59'),
 ('Unnamed: 40', 'Unnamed: 60'),
 ('Unnamed: 40', 'Unnamed: 61'),
 ('Unnamed: 41', 'Unnamed: 42'),
 ('Unnamed: 41', 'Unnamed: 43'),
 ('Unnamed: 41', 'Unnamed: 44'),
 ('Unnamed: 41', 'Unnamed: 45'),
 ('Unnamed: 41', 'Unnamed: 46'),
 ('Unnamed: 41', 'Unnamed: 47'),
 ('Unnamed: 41', 'Unnamed: 48'),
 ('Unnamed: 41', 'Unnamed: 49'),
 ('Unnamed: 41', 'Unnamed: 50'),
 ('Unnamed: 41', 'Unnamed: 51'),
 ('Unnamed: 41', 'Unnamed: 52'),
 ('Unnamed: 41', 'Unnamed: 53'),
 ('Unnamed: 41', 'Unnamed: 54'),
 ('Unnamed: 41', 'Unnamed: 55'),
 ('Unnamed: 41', 'Unnamed: 56'),
 ('Unnamed: 41', 'Unnamed: 57'),
 ('Unnamed: 41', 'Unnamed: 58'),
 ('Unnamed: 41', 'Unnamed: 59'),
 ('Unnamed: 41', 'Unnamed: 60'),
 ('Unnamed: 41', 'Unnamed: 61'),
 ('Unnamed: 42', 'Unnamed: 43'),
 ('Unnamed: 42', 'Unnamed: 44'),
 ('Unnamed: 42', 'Unnamed: 45'),
 ('Unnamed: 42', 'Unnamed: 46'),
 ('Unnamed: 42', 'Unnamed: 47'),
 ('Unnamed: 42', 'Unnamed: 48'),
 ('Unnamed: 42', 'Unnamed: 49'),
 ('Unnamed: 42', 'Unnamed: 50'),
 ('Unnamed: 42', 'Unnamed: 51'),
 ('Unnamed: 42', 'Unnamed: 52'),
 ('Unnamed: 42', 'Unnamed: 53'),
 ('Unnamed: 42', 'Unnamed: 54'),
 ('Unnamed: 42', 'Unnamed: 55'),
 ('Unnamed: 42', 'Unnamed: 56'),
 ('Unnamed: 42', 'Unnamed: 57'),
 ('Unnamed: 42', 'Unnamed: 58'),
 ('Unnamed: 42', 'Unnamed: 59'),
 ('Unnamed: 42', 'Unnamed: 60'),
 ('Unnamed: 42', 'Unnamed: 61'),
 ('Unnamed: 43', 'Unnamed: 44'),
 ('Unnamed: 43', 'Unnamed: 45'),
 ('Unnamed: 43', 'Unnamed: 46'),
 ('Unnamed: 43', 'Unnamed: 47'),
 ('Unnamed: 43', 'Unnamed: 48'),
 ('Unnamed: 43', 'Unnamed: 49'),
 ('Unnamed: 43', 'Unnamed: 50'),
 ('Unnamed: 43', 'Unnamed: 51'),
 ('Unnamed: 43', 'Unnamed: 52'),
 ('Unnamed: 43', 'Unnamed: 53'),
 ('Unnamed: 43', 'Unnamed: 54'),
 ('Unnamed: 43', 'Unnamed: 55'),
 ('Unnamed: 43', 'Unnamed: 56'),
 ('Unnamed: 43', 'Unnamed: 57'),
 ('Unnamed: 43', 'Unnamed: 58'),
 ('Unnamed: 43', 'Unnamed: 59'),
 ('Unnamed: 43', 'Unnamed: 60'),
 ('Unnamed: 43', 'Unnamed: 61'),
 ('Unnamed: 44', 'Unnamed: 45'),
 ('Unnamed: 44', 'Unnamed: 46'),
 ('Unnamed: 44', 'Unnamed: 47'),
 ('Unnamed: 44', 'Unnamed: 48'),
 ('Unnamed: 44', 'Unnamed: 49'),
 ('Unnamed: 44', 'Unnamed: 50'),
 ('Unnamed: 44', 'Unnamed: 51'),
 ('Unnamed: 44', 'Unnamed: 52'),
 ('Unnamed: 44', 'Unnamed: 53'),
 ('Unnamed: 44', 'Unnamed: 54'),
 ('Unnamed: 44', 'Unnamed: 55'),
 ('Unnamed: 44', 'Unnamed: 56'),
 ('Unnamed: 44', 'Unnamed: 57'),
 ('Unnamed: 44', 'Unnamed: 58'),
 ('Unnamed: 44', 'Unnamed: 59'),
 ('Unnamed: 44', 'Unnamed: 60'),
 ('Unnamed: 44', 'Unnamed: 61'),
 ('Unnamed: 45', 'Unnamed: 46'),
 ('Unnamed: 45', 'Unnamed: 47'),
 ('Unnamed: 45', 'Unnamed: 48'),
 ('Unnamed: 45', 'Unnamed: 49'),
 ('Unnamed: 45', 'Unnamed: 50'),
 ('Unnamed: 45', 'Unnamed: 51'),
 ('Unnamed: 45', 'Unnamed: 52'),
 ('Unnamed: 45', 'Unnamed: 53'),
 ('Unnamed: 45', 'Unnamed: 54'),
 ('Unnamed: 45', 'Unnamed: 55'),
 ('Unnamed: 45', 'Unnamed: 56'),
 ('Unnamed: 45', 'Unnamed: 57'),
 ('Unnamed: 45', 'Unnamed: 58'),
 ('Unnamed: 45', 'Unnamed: 59'),
 ('Unnamed: 45', 'Unnamed: 60'),
 ('Unnamed: 45', 'Unnamed: 61'),
 ('Unnamed: 46', 'Unnamed: 47'),
 ('Unnamed: 46', 'Unnamed: 48'),
 ('Unnamed: 46', 'Unnamed: 49'),
 ('Unnamed: 46', 'Unnamed: 50'),
 ('Unnamed: 46', 'Unnamed: 51'),
 ('Unnamed: 46', 'Unnamed: 52'),
 ('Unnamed: 46', 'Unnamed: 53'),
 ('Unnamed: 46', 'Unnamed: 54'),
 ('Unnamed: 46', 'Unnamed: 55'),
 ('Unnamed: 46', 'Unnamed: 56'),
 ('Unnamed: 46', 'Unnamed: 57'),
 ('Unnamed: 46', 'Unnamed: 58'),
 ('Unnamed: 46', 'Unnamed: 59'),
 ('Unnamed: 46', 'Unnamed: 60'),
 ('Unnamed: 46', 'Unnamed: 61'),
 ('Unnamed: 47', 'Unnamed: 48'),
 ('Unnamed: 47', 'Unnamed: 49'),
 ('Unnamed: 47', 'Unnamed: 50'),
 ('Unnamed: 47', 'Unnamed: 51'),
 ('Unnamed: 47', 'Unnamed: 52'),
 ('Unnamed: 47', 'Unnamed: 53'),
 ('Unnamed: 47', 'Unnamed: 54'),
 ('Unnamed: 47', 'Unnamed: 55'),
 ('Unnamed: 47', 'Unnamed: 56'),
 ('Unnamed: 47', 'Unnamed: 57'),
 ('Unnamed: 47', 'Unnamed: 58'),
 ('Unnamed: 47', 'Unnamed: 59'),
 ('Unnamed: 47', 'Unnamed: 60'),
 ('Unnamed: 47', 'Unnamed: 61'),
 ('Unnamed: 48', 'Unnamed: 49'),
 ('Unnamed: 48', 'Unnamed: 50'),
 ('Unnamed: 48', 'Unnamed: 51'),
 ('Unnamed: 48', 'Unnamed: 52'),
 ('Unnamed: 48', 'Unnamed: 53'),
 ('Unnamed: 48', 'Unnamed: 54'),
 ('Unnamed: 48', 'Unnamed: 55'),
 ('Unnamed: 48', 'Unnamed: 56'),
 ('Unnamed: 48', 'Unnamed: 57'),
 ('Unnamed: 48', 'Unnamed: 58'),
 ('Unnamed: 48', 'Unnamed: 59'),
 ('Unnamed: 48', 'Unnamed: 60'),
 ('Unnamed: 48', 'Unnamed: 61'),
 ('Unnamed: 49', 'Unnamed: 50'),
 ('Unnamed: 49', 'Unnamed: 51'),
 ('Unnamed: 49', 'Unnamed: 52'),
 ('Unnamed: 49', 'Unnamed: 53'),
 ('Unnamed: 49', 'Unnamed: 54'),
 ('Unnamed: 49', 'Unnamed: 55'),
 ('Unnamed: 49', 'Unnamed: 56'),
 ('Unnamed: 49', 'Unnamed: 57'),
 ('Unnamed: 49', 'Unnamed: 58'),
 ('Unnamed: 49', 'Unnamed: 59'),
 ('Unnamed: 49', 'Unnamed: 60'),
 ('Unnamed: 49', 'Unnamed: 61'),
 ('Unnamed: 50', 'Unnamed: 51'),
 ('Unnamed: 50', 'Unnamed: 52'),
 ('Unnamed: 50', 'Unnamed: 53'),
 ('Unnamed: 50', 'Unnamed: 54'),
 ('Unnamed: 50', 'Unnamed: 55'),
 ('Unnamed: 50', 'Unnamed: 56'),
 ('Unnamed: 50', 'Unnamed: 57'),
 ('Unnamed: 50', 'Unnamed: 58'),
 ('Unnamed: 50', 'Unnamed: 59'),
 ('Unnamed: 50', 'Unnamed: 60'),
 ('Unnamed: 50', 'Unnamed: 61'),
 ('Unnamed: 51', 'Unnamed: 52'),
 ('Unnamed: 51', 'Unnamed: 53'),
 ('Unnamed: 51', 'Unnamed: 54'),
 ('Unnamed: 51', 'Unnamed: 55'),
 ('Unnamed: 51', 'Unnamed: 56'),
 ('Unnamed: 51', 'Unnamed: 57'),
 ('Unnamed: 51', 'Unnamed: 58'),
 ('Unnamed: 51', 'Unnamed: 59'),
 ('Unnamed: 51', 'Unnamed: 60'),
 ('Unnamed: 51', 'Unnamed: 61'),
 ('Unnamed: 52', 'Unnamed: 53'),
 ('Unnamed: 52', 'Unnamed: 54'),
 ('Unnamed: 52', 'Unnamed: 55'),
 ('Unnamed: 52', 'Unnamed: 56'),
 ('Unnamed: 52', 'Unnamed: 57'),
 ('Unnamed: 52', 'Unnamed: 58'),
 ('Unnamed: 52', 'Unnamed: 59'),
 ('Unnamed: 52', 'Unnamed: 60'),
 ('Unnamed: 52', 'Unnamed: 61'),
 ('Unnamed: 53', 'Unnamed: 54'),
 ('Unnamed: 53', 'Unnamed: 55'),
 ('Unnamed: 53', 'Unnamed: 56'),
 ('Unnamed: 53', 'Unnamed: 57'),
 ('Unnamed: 53', 'Unnamed: 58'),
 ('Unnamed: 53', 'Unnamed: 59'),
 ('Unnamed: 53', 'Unnamed: 60'),
 ('Unnamed: 53', 'Unnamed: 61'),
 ('Unnamed: 54', 'Unnamed: 55'),
 ('Unnamed: 54', 'Unnamed: 56'),
 ('Unnamed: 54', 'Unnamed: 57'),
 ('Unnamed: 54', 'Unnamed: 58'),
 ('Unnamed: 54', 'Unnamed: 59'),
 ('Unnamed: 54', 'Unnamed: 60'),
 ('Unnamed: 54', 'Unnamed: 61'),
 ('Unnamed: 55', 'Unnamed: 56'),
 ('Unnamed: 55', 'Unnamed: 57'),
 ('Unnamed: 55', 'Unnamed: 58'),
 ('Unnamed: 55', 'Unnamed: 59'),
 ('Unnamed: 55', 'Unnamed: 60'),
 ('Unnamed: 55', 'Unnamed: 61'),
 ('Unnamed: 56', 'Unnamed: 57'),
 ('Unnamed: 56', 'Unnamed: 58'),
 ('Unnamed: 56', 'Unnamed: 59'),
 ('Unnamed: 56', 'Unnamed: 60'),
 ('Unnamed: 56', 'Unnamed: 61'),
 ('Unnamed: 57', 'Unnamed: 58'),
 ('Unnamed: 57', 'Unnamed: 59'),
 ('Unnamed: 57', 'Unnamed: 60'),
 ('Unnamed: 57', 'Unnamed: 61'),
 ('Unnamed: 58', 'Unnamed: 59'),
 ('Unnamed: 58', 'Unnamed: 60'),
 ('Unnamed: 58', 'Unnamed: 61'),
 ('Unnamed: 59', 'Unnamed: 60'),
 ('Unnamed: 59', 'Unnamed: 61'),
 ('Unnamed: 60', 'Unnamed: 61')]

In [13]:
df["ResponseType"].value_counts(dropna=False)

ResponseType
Promoter     13756
Passive       9032
Detractor     8681
Name: count, dtype: int64

## Data Cleaning

**Remove completely empty columns**

In [14]:
df = df.dropna(axis=1, how="all")

In [16]:
# drop the duplicate columns
df = df.drop(columns=[
    "PipelineInfo_ClientCountry.1",
    "Tenant_Country.1"
], errors="ignore")

In [18]:
#Remove CPU Architecture because it is almost completely missing
df = df.drop(columns=["R7_DeviceInfo_CpuArchitecture"], errors="ignore")

In [19]:
df["Feedback_DateTime"] = pd.to_datetime(
    df["Feedback_DateTime"],
    errors="coerce"
)

In [20]:
df["FirstSeenTime_Date"] = pd.to_datetime(
    df["FirstSeenTime_Date"],
    errors="coerce"
)

In [21]:
df.loc[
    df["FirstSeenTime_Date"] == "1970-01-01",
    "FirstSeenTime_Date"
] = pd.NaT

In [22]:
df = df.drop_duplicates()

In [27]:
print("Final shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Missing Feedback IDs:", df["Feedback_ID"].isna().sum())
print("Missing Ratings:", df["Feedback_Rating"].isna().sum())
print("Missing ResponseType:", df["ResponseType"].isna().sum())

Final shape: (31469, 26)
Duplicate rows: 0
Missing Feedback IDs: 0
Missing Ratings: 0
Missing ResponseType: 0